<!doctype html>
<html lang="en">
    <head>
        <title>Terms & Conditions | Del Monte Honeyglow Pineapple</title>
        <?php include('includes/meta.php'); ?>
        <?php include('includes/favicon.php'); ?>
        <?php include('includes/styles.php'); ?>
    </head>
    <body class="terms-page">
        <div class="page-container">
			<?php include('includes/preloader.php'); ?>
			<?php include('includes/browserupgrade.php'); ?>
			<?php include('includes/header.php'); ?>
			<main>
				<div class="page-wrapper">
					<h1>Terms & Conditions</h1>
					<h2>Official Rules for the April 2021 Fresh Del Monte<sup>&reg;</sup> <br />Chief of Sweetness Campaign</h2>
					<h3>No Purchase Necessary. A Purchase Will Not Increase Your Chances of Being Chosen.</h3>
					<ol>
						<li><strong>Eligibility:</strong> The Contest is open only to legal residents of the United States who are at least eighteen (18) years old and over the age of majority in the state in which they reside. Employees of Del Monte Fresh Produce N.A., Inc. (“Sponsor”), Del Monte Fresh Produce Company, Mann Packing Co., Inc., and BML Public Relations as well as the immediate family (spouse, parents, siblings, and children) and household members of those employees, are not eligible to enter.</li>
						<li><strong>Entry Period:</strong> The Contest begins on April TBD, 2021 at 9:00AM EST and ends on May TBD 2021 at 11:59PM EST (“Entry Period”). Entries submitted before or after the Entry Period will not be eligible. Sponsor’s computer is the official time-keeping device for the Contest.</li>
						<li><strong>How to Enter:</strong> Visit <a href="https://honeyglowpineapple.com" target="_blank">HoneyglowPineapple.com</a> and describe in 250 words or less why you are the sweetest person in the country and why you deserve to be chosen as the Chief of Sweetness for Del Monte Fresh Produce. There is a limit of one (1) entry per person.</li>
						<li><strong>Sponsor’s Rights to Entries:</strong> By entering, you irrevocably grant Sponsor, its agents, licensees, and assigns the unconditional and perpetual (non-exclusive) right and permission to reproduce, encode, store, copy, transmit, publish, post, broadcast, display, publicly perform, adapt, modify, create derivative works of, exhibit, and otherwise use your entry as-is or as-edited (with or without using your name) in any media throughout the world for any purpose, without limitation, and without additional review, compensation, or approval from you or any other party. You are solely responsible for the content of your comments and by entering you agree not to post any content that is obscene, pornographic, racist, libelous, illegal or otherwise objectionable.</li>
						<li><strong>Judging:</strong> On TBD, Del Monte Fresh Produce will select the winner based upon the strongest 250-word submission and who they believe displayed the most kindness in their submission. Within 5 business days of the Judging, Del Monte Fresh Produce will attempt to notify potential winner via submitted email address. The odds of winning depend on the relative performance of the entrants.</li>
						<li><strong>Potential Winner Requirements:</strong> Except where prohibited, potential winners may be required to complete and return a declaration of eligibility and liability/publicity release. If a potential winner fails to sign and return these documents within the required time period, that potential winner waives their entry and an alternate winner will be selected.</li>
						<li><strong>Prize(s):</strong> The Chief of Sweetness will receive a year’s supply of free Honeyglow Pineapples (one shipment of produce per month for 12 months.). They will also receive Del Monte Fresh Produce swag, including various branded items (TBD). All prizes combined are valued at $375. A winner is responsible for paying any applicable income taxes and any and all other costs and expenses not listed above. Any prize details not specified above will be determined by Sponsor, in its sole discretion. A prize may not be transferred prior to award and must be accepted as awarded. A winner may not request cash or a substitute prize; however, Sponsor reserves the right to substitute a prize with another prize of equal or greater value if the advertised prize is not available for any reason, as determined by Sponsor, in its sole discretion.</li>
						<li><strong>General Conditions:</strong> In the event that the operation, security, or administration of the Contest is impaired in any way, Sponsor may, in its sole discretion, either: (a) suspend the Contest to address the impairment and then resume the Contest; or (b) award the prizes according to the criteria described above from among the eligible entries received up to the time of the impairment. Sponsor reserves the right, in its sole discretion, to disqualify and seek damages from any individual who tampers with the operation of the Contest, violates these Official Rules, or acts in a disruptive or unsportsmanlike manner. Sponsor’s failure to enforce any term of these Official Rules shall not constitute a waiver of that provision. Proof of sending any communication to Sponsor by mail shall not be deemed proof of receipt of that communication. The Contest is subject to federal, state, and local laws and regulations.</li>
						<li><strong>Privacy and Publicity:</strong> Any information you submit as part of the Contest will be used in accordance with Sponsor’s <a href="https://www.freshdelmonte.com/privacy-policy" target="_blank">Privacy Policy</a>. Except where prohibited, participation in the Contest constitutes your consent to Sponsor’s use of your name, likeness, voice, opinions, biographical information, and state of residence for promotional purposes in any media without further payment or consideration.</li>
						<li><strong>Release and Limitations of Liability:</strong> By entering, you agree to release and hold harmless Sponsor, its parent, subsidiaries and affiliates,  Subsidiaries, affiliates, and advertising and Contest agencies, and each of their respective officers, directors, employees, and agents (collectively, the “Released Parties”) from and against any claim or cause of action arising out of participation in the Contest or receipt or use of any prize, including, but not limited to (a) unauthorized human intervention in the Contest; (b) technical errors related to computers, servers, providers, or telephone or network lines; (c) any errors on the social media platforms that may prevent an individual from participating or receiving direct messages; (d) printing errors; (e) lost, late, postage-due, misdirected, or undeliverable mail; (f) errors in the administration of the Contest or the processing of posts; or (g) injury or damage to persons or property. You further agree that in any cause of action, in no event shall the Released Parties be liable for attorneys’ fees or other legal costs. You waive the right to claim any damages whatsoever, including, but not limited to, punitive, consequential, direct, or indirect damages.</li>
						<li><strong>Disputes:</strong> You agree that any and all disputes, claims and causes of action arising out of, or connected with, the Contest or any prize awarded shall be resolved individually, without resort to any form of class action, and exclusively by the appropriate state or federal court located in the state of Florida. All issues and questions concerning the construction, validity, interpretation, and enforceability of these Official Rules, your rights and obligations, or the rights and obligations of the Sponsor in connection with the Contest, shall be governed by, and construed in accordance with, the laws of Florida, without giving effect to any choice of law or conflict of law rules (whether of Florida or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than Florida.</li>
						<li><strong>Winners:</strong> To request a list of people who have won a prize worth over $25, send a self-addressed, stamped envelope to Del Monte Fresh Produce, Attention: Marketing, 241 Sevilla Ave  Coral Gables, FL 33134 . Requests must be received within thirty (30) days of the end of the Entry Period.</li>
						<li><strong>Sponsor:</strong> The Contest is sponsored by Del Monte Fresh Produce N.A., Inc.</li>
					</ol>
				</div>
			</main>
			<?php include('includes/footer.php'); ?>
		</div>
        <?php include('includes/scripts.php'); ?>
    </body>
</html>